export const FETCH_REQUEST = "FETCH_REQUEST";

export const AUTH_SUCCEEDED = "AUTH_SUCCEEDED";

export const FETCH_REQUEST_FAILED = "FETCH_REQUEST_FAILED";
//
export const CLEAR_ERROR = "CLEAR_ERROR";
//

export const LOGOUT = "LOGOUT";

export const USERS_FETCH_SUCCEEDED = "USERS_FETCH_SUCCEEDED";
